def quotes():
    return [
        "Never Underestimate the Importance of Being Properly Caffeinated.",
        "Good Coffee – Cheaper than Prozac!",
        "Coffee is a way of stealing time which should by rights belong to your older self.",
        "No one can understand the truth until he drinks of coffee’s frothy goodness.",
        "To an old man a cup of coffee is like the door pos…f an old house — it sustains and strengthens him.",
        "People say money can’t buy happiness. They Lie. Money buys Coffee, Coffee makes Me Happy!",
        " is like a hairless cat, it exists, but that doesn’t make it right.",
        "Coffee makes us severe, and grave, and philosophical.",
        "I orchestrate my mornings to the tune of coffee.",
        "Conscience keeps more people awake than coffee.",
        "Should I kill myself, or have a cup of coffee?",
        "My coffee machine is the most beautiful person in the world to me.",
        "Sometimes I stay up so late that I have my morning coffee before I go to bed.",
        "Good communication is as stimulating as black coffee, and just as hard to sleep after.",
        "Drinking beer in a coffee mug. I feel like I am cheating on my coffee.",
        "We are cups, constantly and quietly being filled. …p ourselves over and let the beautiful stuff out.",
        "Coffee is the best thing to douse the sunrise with.",
        "Everyone should believe in something. I believe I will have another coffee.",
        "Coffee should be black as Hell, strong as death, and sweet as love.",
        "I don’t know what I’d do without coffee. I’m guessing 25 to life.",
        "Science may never come up with a better office communication system than the coffee break.",
        "A 41-inch bust and a lot of perseverance will get you more than a cup of coffee – a lot more.",
        "Good communication is just as stimulating as black coffee, and just as hard to sleep after.",
        "7 days without coffee makes one WEAK.",
        "Caffeine — It maintains my sunny personality.",
        "The powers of a man’s mind are directly proportional to the quantity of coffee he drank.",
        "I’m going to start measuring the complexity of cod…offee cups. “This was a five-espresso algorithm.”",
        "A mathematician is a device for turning coffee into theorems.",
        "Coffee smells like freshly ground heaven.",
        "Decaf? No, it’s dangerous to dilute my caffeine stream.",
        "Doctors found traces of blood in my coffee stream.",
        "Did I run out of caffeine or are you really that boring?",
        "If it wasn’t for coffee, I’d have no discernible personality at all.",
        "Compared to Clinton, I feel like a loser. I can’t even get the intern to make me coffee!",
        "Coffee which makes the politician wise, and see through all things with his half-shut eyes.",
        "I like my coffee with cream and my literature with optimism.",
        "I like my coffee strong and my women weak.",
        "Coffee. Creative lighter fluid.",
        "A morning without coffee is like sleep.",
        "Every morning I long to hold you…I need you, I wan…, your smell, your taste…ohhh coffee, I love you.",
        "Drink coffee! Do Stupid Things Faster with More Energy.",
        "Coffee! Is the planet shaking or is just me?",
        "How far behind would technology be, if no one ever discovered coffee?",
        "I’m a romantic. I like cold Coffee and orgasms tha…s after I’ve put on my clothes and paid the lady.",
        "Even bad coffee is better… than no Coffee at all.",
        "Adventure in life is good… consistency in Coffee even better.",
        "I like instant gratification. It’s like instant Coffee, only it won’t keep you up all night.",
        "What do you want?… Just Coffee. Black – like my soul.",
        "I would rather suffer with coffee than be senseless.",
        "I never drink coffee at lunch. I find it keeps me awake for the afternoon.",
        "Television is not real life. In real life people a…lly have to leave the coffee shop and go to jobs.",
        "Like everyone else who makes the mistake of gettin…der, I begin each day with coffee and obituaries.",
        "If this is coffee, please bring me some tea; but if this is tea, please bring me some coffee.",
        "A cup of gourmet coffee shared with a friend is happiness tasted and time well spent.",
        "Adventure in life is good. Consistency in coffee even better.",
        "A morning without coffee is like sleep.",
        "Life’s too short to drink cheap coffee.",
        "Everybody should believe in something. I believe I’ll have another coffee.",
        "The road to success is paved in coffee.",
        "This coffee tastes like mud! Well, it was ground this morning.",
        "I think if I were a woman I’d wear coffee as a perfume.",
        "There is no live without water. Because water is needed to make coffee.",
        "To drink is human. To drink coffee is divine.",
        "Given enough coffee I could rule the world.",
        "A cup of coffee shared with a friend is happiness tasted and time well spent.",
        "I don’t have a problem with caffeine. I have a problem without it.",
        "Drink Coffee. Do stupid things even faster with more energy.",
        "Caffeine-The other Vitamin C.",
        "I have measured out my life with coffee spoons.",
        "Black as the devil, hot as hell, pure as an angel, sweet as love.",
        "You can tell when you have crossed the frontier into Germany because of the badness of the coffee.",
        "Forever: Time it takes to brew the first pot of coffee in the morning.",
        "Caffeine isn’t a drug, it’s a vitamin.",
        "Coffee is a beverage that puts one to sleep when not drank.",
        "Sleep is a symptom of caffeine deprivation.",
        "Decaffeinated coffee is kind of like kissing your sister.",
        "The first cup is for the guest, the second for enjoyment, the third for the sword.",
        "There’s nothing sweeter than a cup of bitter coffee.",
        "Deja Brew: The feeling that you’ve had this coffee before.",
        "Politics now is rather like going into Starbucks for a coffee.",
        "I judge a restaurant by the bread and by the coffee.",
        "I like cappuccino, actually. But even a bad cup of coffee is better than no coffee at all.",
        "Coffee in England is just toasted milk.",
        "I like my coffee like I like my women. In a plastic cup.",
        "Once you wake up and smell the coffee, it’s hard to go back to sleep.",
        "COFFEE.SYS Not Found: User startup disabled.",
        "C:>http://COFFEE.COM error. Contact programmer J. Valdez.",
        "C:\COFFEE.POT missing (A)bort (R)etry (F)all asleep?",
        "I could serve coffee using my rear as a ledge.",
        "Do you know how helpless you feel if you have a fu…p of coffee in your hand and you start to sneeze?",
        "Like everyone else who makes the mistake of gettin…der, I begin each day with coffee and obituaries.",
        "Do Lipton employees take coffee breaks?",
        "When traveling with someone, take large does of patience and tolerance with your morning coffee.",
        "Our culture runs on coffee and gasoline, the first often tasting like the second."]